apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-secrets
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: global
    namespace: default
roleRef:
  kind: ClusterRole
  name: secret-admin
  apiGroup: rbac.authorization.k8s.io